########
# Configuration.
#
GCC_BIN ?= #/path/to/bin

# Test to perform.
# 1. Execution cost measured in CPU cycles of the vTaskDelayUntil() kernel function.
# 2. Amount of ceil and floor operations performed by the selected Slack Stealing method.
# 3. Execution cost of the selected Slack Stealing method measured in CPU cycles.
# 4. Amount of for and while loops performed by the selected Slack Stealing method.
KERNEL_TEST ?= 1

# Number of tasks.
TASK_COUNT_PARAM ?= 10

# Number of task releases to evaluate.
RELEASE_COUNT_PARAM ?= 10

# Use slack
SLACK ?= 1

# If 1, only calculate slack at the scheduler start.
SLACK_K ?= 0

# Slack method to evaluate:
# 0 = Fixed
# 1 = Davis
SLACK_METHOD ?= 0

# priority levels that are used for slack.
MAX_PRIO ?= 1

TEST_PATH ?= .\tests\2020-01-21\

FREERTOS_KERNEL_VERSION_NUMBER ?= v10.4.1

FREERTOS_KERNEL_VERSION_NUMBER_MAJOR ?= 1

DEBUG = 1

#
# End configuration.
########
