#
# Don't change this file. Copy this file as Makefile.mine and then set the 
# variables. The Makefile.mine will be included by the root Makefile, but 
# ignored by .gitignore.
#
# Targets:
#   Examples (see examples directory):
#     example1
#     example2
#     example3
#
TARGET ?= example1

PATH_TO_ARM_GCC ?= #/path/to/gcc/bin

DEBUG ?= 0

#
# Set to:
# - v8.1.2
# - v9.0.0
#
FREERTOS_KERNEL_VERSION_NUMBER ?= v8.1.2
