#
# >>> DON'T CHANGE THIS FILE. <<<
# 
# Copy this file as Makefile.mine and set the variables in that copy. The 
# Makefile.mine will be included by the root Makefile, but ignored by git.
#

#
# Example programs. Set TARGET and APP_NAME:
#
# Targets:
#   lpc1768
#   frdm-k64f
#   edu-ciaa-nxp
#   lm3s6965evb
#
# Se the examples directories for programs for each target.
#
TARGET ?= lpc1768
APP_NAME ?= example1

#
# Set DEBUG to 1 to enable debuggin info.
# - 0: enable -g -0g -gggdb3
# - 1: enable -g -Os
#
DEBUG ?= 0

#
# FreeRTOS version to use when building the example programs.
# Set to:
# - 10.4.1
#
FREERTOS_KERNEL_VERSION_NUMBER ?= 10.4.1

#
# Set TZ to 1 to enable tracing.
# Set TRACEALIZER_VERSION_NUMBER to specify the Tracealyzer version to use:
# - v3.3.1 (for FreeRTOS v10.x)
#
TZ ?= 1
TRACEALIZER_VERSION_NUMBER ?= v3.1.3

#
# ARM toolchain path.
#
#PATH_TO_ARM_GCC ?= /path/to/gcc/bin

#
# OpenOCD binary path
#
#OOCD ?= /path/to/openocd
