#
# Don't change this file. Copy this file as Makefile.mine and then set the 
# variables. The Makefile.mine will be included by the root Makefile, but 
# ignored by .gitignore.
#

#
# Example programs. Set TARGET and APP_NAME according to these values:
#
# Targets:
#   lpc1768
#   frdm-k64f
#   edu-ciaa-nxp
#
# Examples (see examples directory):
#   example1 - rm
#   example2 - rm + ss
#
TARGET ?= lpc1768
APP_NAME ?= example1

#
# Specify the path to the arm toolchain.
#
#PATH_TO_ARM_GCC ?= #/path/to/gcc/bin

#
# Set DEBUG to 1 to enable debuggin info.
# - 0: enable -g -0g -gggdb3
# - 1: enable -g -Os
#
#DEBUG ?= 1

#
# FreeRTOS version to use when building the example programs.
# Set to:
# - v8.1.2
# - v9.0.0
#
FREERTOS_KERNEL_VERSION_NUMBER ?= v9.0.0

#
# Set TZ to 1 to enable tracing.
# Set TRACEALIZER_VERSION_NUMBER to specify the Tracealyzer version to use:
# - v3.0.2 (for FreeRTOS v8.1.2)
# - v3.1.3 (for FreeRTOS v9.0.0)
#
TZ ?= 1
TRACEALIZER_VERSION_NUMBER ?= v3.1.3

#
# Specify the OpenOCD binary path
#
#OOCD ?= /path/to/openocd
